/*
작성 일자 : 230921
수정 일자 : 
작 성 자 : 조건영
작성 목적 : 테이블 생성을 위한 사용자 타입 생성 및 권한 부여
*/



-- 사용자 타입 생성
create type sc_khb_srv.addr_nv1000 from nvarchar(1000);
create type sc_khb_srv.amt_n18 from numeric(18);
create type sc_khb_srv.area_d19_9 from decimal(19, 9);
create type sc_khb_srv.cd_v2 from varchar(2);
create type sc_khb_srv.cd_v20 from varchar(20);
create type sc_khb_srv.cn_nv4000 from nvarchar(4000);
create type sc_khb_srv.cn_nvmax from nvarchar(max);
create type sc_khb_srv.cnt_n15 from numeric(15);
create type sc_khb_srv.cntom_n15 from numeric(15);
create type sc_khb_srv.cours_v100 from varchar(100);
create type sc_khb_srv.cpcty_d25_15 from decimal(25, 15);
create type sc_khb_srv.crdnt_v500 from varchar(500);
create type sc_khb_srv.ct_n18 from numeric(18);
create type sc_khb_srv.cycle_v20 from varchar(20);
create type sc_khb_srv.day_nv100 from nvarchar(100);
create type sc_khb_srv.de_v10 from varchar(10);
create type sc_khb_srv.dt from datetime;
create type sc_khb_srv.dt_v10 from varchar(10);
create type sc_khb_srv.email_v320 from varchar(320);
create type sc_khb_srv.fee_n18 from numeric(18);
create type sc_khb_srv.fxno_v30 from varchar(30);
create type sc_khb_srv.hm_c4 from char(4);
create type sc_khb_srv.hms_c6 from char(6);
create type sc_khb_srv.id_nv100 from nvarchar(100);
create type sc_khb_srv.innb_v20 from varchar(20);
create type sc_khb_srv.ip_v100 from varchar(100);
create type sc_khb_srv.lat_d12_10 from decimal(12, 10);
create type sc_khb_srv.list_nv1000 from nvarchar(1000);
create type sc_khb_srv.lot_d13_10 from decimal(13, 10);
create type sc_khb_srv.lotno_nv100 from nvarchar(100);
create type sc_khb_srv.mno_n4 from numeric(4);
create type sc_khb_srv.mt_c2 from char(2);
create type sc_khb_srv.nm_nv500 from nvarchar(500);
create type sc_khb_srv.no_n15 from numeric(15);
create type sc_khb_srv.no_v200 from varchar(200);
create type sc_khb_srv.ordr_n5 from numeric(5);
create type sc_khb_srv.password_v500 from varchar(500);
create type sc_khb_srv.pc_n10 from numeric(10);
create type sc_khb_srv.pd_nv50 from nvarchar(50);
create type sc_khb_srv.pk_n18 from numeric(18);
create type sc_khb_srv.premium_n18 from numeric(18);
create type sc_khb_srv.pyeong_d19_9 from decimal(19, 9);
create type sc_khb_srv.rank_n5 from numeric(5);
create type sc_khb_srv.rt_d19_9 from decimal(19, 9);
create type sc_khb_srv.size_v20 from varchar(20);
create type sc_khb_srv.sn_v200 from varchar(200);
create type sc_khb_srv.sno_n4 from numeric(4);
create type sc_khb_srv.telno_v30 from varchar(30);
create type sc_khb_srv.totar_d19_9 from decimal(19, 9);
create type sc_khb_srv.url_nv4000 from nvarchar(4000);
create type sc_khb_srv.vl_d25_15 from decimal(25, 15);
create type sc_khb_srv.vl_v100 from varchar(100);
create type sc_khb_srv.year_c4 from char(4);
create type sc_khb_srv.ym_c6 from char(6);
create type sc_khb_srv.yn_c1 from char(1);
create type sc_khb_srv.zip_c5 from char(5);





-- 권한 부여
/*us_khb_adm*/
grant execute on type::sc_khb_srv.addr_nv1000 to us_khb_adm;
grant execute on type::sc_khb_srv.amt_n18 to us_khb_adm;
grant execute on type::sc_khb_srv.area_d19_9 to us_khb_adm;
grant execute on type::sc_khb_srv.cd_v20 to us_khb_adm;
grant execute on type::sc_khb_srv.cn_nv4000 to us_khb_adm;
grant execute on type::sc_khb_srv.cn_nvmax to us_khb_adm;
grant execute on type::sc_khb_srv.cnt_n15 to us_khb_adm;
grant execute on type::sc_khb_srv.cntom_n15 to us_khb_adm;
grant execute on type::sc_khb_srv.cours_v100 to us_khb_adm;
grant execute on type::sc_khb_srv.cpcty_d25_15 to us_khb_adm;
grant execute on type::sc_khb_srv.crdnt_v500 to us_khb_adm;
grant execute on type::sc_khb_srv.ct_n18 to us_khb_adm;
grant execute on type::sc_khb_srv.cycle_v20 to us_khb_adm;
grant execute on type::sc_khb_srv.day_nv100 to us_khb_adm;
grant execute on type::sc_khb_srv.de_v10 to us_khb_adm;
grant execute on type::sc_khb_srv.dt to us_khb_adm;
grant execute on type::sc_khb_srv.dt_v10 to us_khb_adm;
grant execute on type::sc_khb_srv.email_v320 to us_khb_adm;
grant execute on type::sc_khb_srv.fee_n18 to us_khb_adm;
grant execute on type::sc_khb_srv.fxno_v30 to us_khb_adm;
grant execute on type::sc_khb_srv.hm_c4 to us_khb_adm;
grant execute on type::sc_khb_srv.hms_c6 to us_khb_adm;
grant execute on type::sc_khb_srv.id_nv100 to us_khb_adm;
grant execute on type::sc_khb_srv.innb_v20 to us_khb_adm;
grant execute on type::sc_khb_srv.ip_v100 to us_khb_adm;
grant execute on type::sc_khb_srv.lat_d12_10 to us_khb_adm;
grant execute on type::sc_khb_srv.list_nv1000 to us_khb_adm;
grant execute on type::sc_khb_srv.lot_d13_10 to us_khb_adm;
grant execute on type::sc_khb_srv.lotno_nv100 to us_khb_adm;
grant execute on type::sc_khb_srv.mno_n4 to us_khb_adm;
grant execute on type::sc_khb_srv.mt_c2 to us_khb_adm;
grant execute on type::sc_khb_srv.nm_nv500 to us_khb_adm;
grant execute on type::sc_khb_srv.no_n15 to us_khb_adm;
grant execute on type::sc_khb_srv.no_v200 to us_khb_adm;
grant execute on type::sc_khb_srv.ordr_n5 to us_khb_adm;
grant execute on type::sc_khb_srv.password_v500 to us_khb_adm;
grant execute on type::sc_khb_srv.pc_n10 to us_khb_adm;
grant execute on type::sc_khb_srv.pd_nv50 to us_khb_adm;
grant execute on type::sc_khb_srv.pk_n18 to us_khb_adm;
grant execute on type::sc_khb_srv.premium_n18 to us_khb_adm;
grant execute on type::sc_khb_srv.pyeong_d19_9 to us_khb_adm;
grant execute on type::sc_khb_srv.rank_n5 to us_khb_adm;
grant execute on type::sc_khb_srv.rt_d19_9 to us_khb_adm;
grant execute on type::sc_khb_srv.size_v20 to us_khb_adm;
grant execute on type::sc_khb_srv.sn_v200 to us_khb_adm;
grant execute on type::sc_khb_srv.sno_n4 to us_khb_adm;
grant execute on type::sc_khb_srv.telno_v30 to us_khb_adm;
grant execute on type::sc_khb_srv.totar_d19_9 to us_khb_adm;
grant execute on type::sc_khb_srv.url_nv4000 to us_khb_adm;
grant execute on type::sc_khb_srv.vl_d25_15 to us_khb_adm;
grant execute on type::sc_khb_srv.vl_v100 to us_khb_adm;
grant execute on type::sc_khb_srv.year_c4 to us_khb_adm;
grant execute on type::sc_khb_srv.ym_c6 to us_khb_adm;
grant execute on type::sc_khb_srv.yn_c1 to us_khb_adm;
grant execute on type::sc_khb_srv.zip_c5 to us_khb_adm;


/*us_khb_agnt*/
grant execute on type::sc_khb_srv.addr_nv1000 to us_khb_agnt;
grant execute on type::sc_khb_srv.amt_n18 to us_khb_agnt;
grant execute on type::sc_khb_srv.area_d19_9 to us_khb_agnt;
grant execute on type::sc_khb_srv.cd_v20 to us_khb_agnt;
grant execute on type::sc_khb_srv.cn_nv4000 to us_khb_agnt;
grant execute on type::sc_khb_srv.cn_nvmax to us_khb_agnt;
grant execute on type::sc_khb_srv.cnt_n15 to us_khb_agnt;
grant execute on type::sc_khb_srv.cntom_n15 to us_khb_agnt;
grant execute on type::sc_khb_srv.cours_v100 to us_khb_agnt;
grant execute on type::sc_khb_srv.cpcty_d25_15 to us_khb_agnt;
grant execute on type::sc_khb_srv.crdnt_v500 to us_khb_agnt;
grant execute on type::sc_khb_srv.ct_n18 to us_khb_agnt;
grant execute on type::sc_khb_srv.cycle_v20 to us_khb_agnt;
grant execute on type::sc_khb_srv.day_nv100 to us_khb_agnt;
grant execute on type::sc_khb_srv.de_v10 to us_khb_agnt;
grant execute on type::sc_khb_srv.dt to us_khb_agnt;
grant execute on type::sc_khb_srv.dt_v10 to us_khb_agnt;
grant execute on type::sc_khb_srv.email_v320 to us_khb_agnt;
grant execute on type::sc_khb_srv.fee_n18 to us_khb_agnt;
grant execute on type::sc_khb_srv.fxno_v30 to us_khb_agnt;
grant execute on type::sc_khb_srv.hm_c4 to us_khb_agnt;
grant execute on type::sc_khb_srv.hms_c6 to us_khb_agnt;
grant execute on type::sc_khb_srv.id_nv100 to us_khb_agnt;
grant execute on type::sc_khb_srv.innb_v20 to us_khb_agnt;
grant execute on type::sc_khb_srv.ip_v100 to us_khb_agnt;
grant execute on type::sc_khb_srv.lat_d12_10 to us_khb_agnt;
grant execute on type::sc_khb_srv.list_nv1000 to us_khb_agnt;
grant execute on type::sc_khb_srv.lot_d13_10 to us_khb_agnt;
grant execute on type::sc_khb_srv.lotno_nv100 to us_khb_agnt;
grant execute on type::sc_khb_srv.mno_n4 to us_khb_agnt;
grant execute on type::sc_khb_srv.mt_c2 to us_khb_agnt;
grant execute on type::sc_khb_srv.nm_nv500 to us_khb_agnt;
grant execute on type::sc_khb_srv.no_n15 to us_khb_agnt;
grant execute on type::sc_khb_srv.no_v200 to us_khb_agnt;
grant execute on type::sc_khb_srv.ordr_n5 to us_khb_agnt;
grant execute on type::sc_khb_srv.password_v500 to us_khb_agnt;
grant execute on type::sc_khb_srv.pc_n10 to us_khb_agnt;
grant execute on type::sc_khb_srv.pd_nv50 to us_khb_agnt;
grant execute on type::sc_khb_srv.pk_n18 to us_khb_agnt;
grant execute on type::sc_khb_srv.premium_n18 to us_khb_agnt;
grant execute on type::sc_khb_srv.pyeong_d19_9 to us_khb_agnt;
grant execute on type::sc_khb_srv.rank_n5 to us_khb_agnt;
grant execute on type::sc_khb_srv.rt_d19_9 to us_khb_agnt;
grant execute on type::sc_khb_srv.size_v20 to us_khb_agnt;
grant execute on type::sc_khb_srv.sn_v200 to us_khb_agnt;
grant execute on type::sc_khb_srv.sno_n4 to us_khb_agnt;
grant execute on type::sc_khb_srv.telno_v30 to us_khb_agnt;
grant execute on type::sc_khb_srv.totar_d19_9 to us_khb_agnt;
grant execute on type::sc_khb_srv.url_nv4000 to us_khb_agnt;
grant execute on type::sc_khb_srv.vl_d25_15 to us_khb_agnt;
grant execute on type::sc_khb_srv.vl_v100 to us_khb_agnt;
grant execute on type::sc_khb_srv.year_c4 to us_khb_agnt;
grant execute on type::sc_khb_srv.ym_c6 to us_khb_agnt;
grant execute on type::sc_khb_srv.yn_c1 to us_khb_agnt;
grant execute on type::sc_khb_srv.zip_c5 to us_khb_agnt;


/*us_khb_com*/
grant execute on type::sc_khb_srv.addr_nv1000 to us_khb_com;
grant execute on type::sc_khb_srv.amt_n18 to us_khb_com;
grant execute on type::sc_khb_srv.area_d19_9 to us_khb_com;
grant execute on type::sc_khb_srv.cd_v20 to us_khb_com;
grant execute on type::sc_khb_srv.cn_nv4000 to us_khb_com;
grant execute on type::sc_khb_srv.cn_nvmax to us_khb_com;
grant execute on type::sc_khb_srv.cnt_n15 to us_khb_com;
grant execute on type::sc_khb_srv.cntom_n15 to us_khb_com;
grant execute on type::sc_khb_srv.cours_v100 to us_khb_com;
grant execute on type::sc_khb_srv.cpcty_d25_15 to us_khb_com;
grant execute on type::sc_khb_srv.crdnt_v500 to us_khb_com;
grant execute on type::sc_khb_srv.ct_n18 to us_khb_com;
grant execute on type::sc_khb_srv.cycle_v20 to us_khb_com;
grant execute on type::sc_khb_srv.day_nv100 to us_khb_com;
grant execute on type::sc_khb_srv.de_v10 to us_khb_com;
grant execute on type::sc_khb_srv.dt to us_khb_com;
grant execute on type::sc_khb_srv.dt_v10 to us_khb_com;
grant execute on type::sc_khb_srv.email_v320 to us_khb_com;
grant execute on type::sc_khb_srv.fee_n18 to us_khb_com;
grant execute on type::sc_khb_srv.fxno_v30 to us_khb_com;
grant execute on type::sc_khb_srv.hm_c4 to us_khb_com;
grant execute on type::sc_khb_srv.hms_c6 to us_khb_com;
grant execute on type::sc_khb_srv.id_nv100 to us_khb_com;
grant execute on type::sc_khb_srv.innb_v20 to us_khb_com;
grant execute on type::sc_khb_srv.ip_v100 to us_khb_com;
grant execute on type::sc_khb_srv.lat_d12_10 to us_khb_com;
grant execute on type::sc_khb_srv.list_nv1000 to us_khb_com;
grant execute on type::sc_khb_srv.lot_d13_10 to us_khb_com;
grant execute on type::sc_khb_srv.lotno_nv100 to us_khb_com;
grant execute on type::sc_khb_srv.mno_n4 to us_khb_com;
grant execute on type::sc_khb_srv.mt_c2 to us_khb_com;
grant execute on type::sc_khb_srv.nm_nv500 to us_khb_com;
grant execute on type::sc_khb_srv.no_n15 to us_khb_com;
grant execute on type::sc_khb_srv.no_v200 to us_khb_com;
grant execute on type::sc_khb_srv.ordr_n5 to us_khb_com;
grant execute on type::sc_khb_srv.password_v500 to us_khb_com;
grant execute on type::sc_khb_srv.pc_n10 to us_khb_com;
grant execute on type::sc_khb_srv.pd_nv50 to us_khb_com;
grant execute on type::sc_khb_srv.pk_n18 to us_khb_com;
grant execute on type::sc_khb_srv.premium_n18 to us_khb_com;
grant execute on type::sc_khb_srv.pyeong_d19_9 to us_khb_com;
grant execute on type::sc_khb_srv.rank_n5 to us_khb_com;
grant execute on type::sc_khb_srv.rt_d19_9 to us_khb_com;
grant execute on type::sc_khb_srv.size_v20 to us_khb_com;
grant execute on type::sc_khb_srv.sn_v200 to us_khb_com;
grant execute on type::sc_khb_srv.sno_n4 to us_khb_com;
grant execute on type::sc_khb_srv.telno_v30 to us_khb_com;
grant execute on type::sc_khb_srv.totar_d19_9 to us_khb_com;
grant execute on type::sc_khb_srv.url_nv4000 to us_khb_com;
grant execute on type::sc_khb_srv.vl_d25_15 to us_khb_com;
grant execute on type::sc_khb_srv.vl_v100 to us_khb_com;
grant execute on type::sc_khb_srv.year_c4 to us_khb_com;
grant execute on type::sc_khb_srv.ym_c6 to us_khb_com;
grant execute on type::sc_khb_srv.yn_c1 to us_khb_com;
grant execute on type::sc_khb_srv.zip_c5 to us_khb_com;


/*us_khb_dev*/
grant execute on type::sc_khb_srv.addr_nv1000 to us_khb_dev;
grant execute on type::sc_khb_srv.amt_n18 to us_khb_dev;
grant execute on type::sc_khb_srv.area_d19_9 to us_khb_dev;
grant execute on type::sc_khb_srv.cd_v20 to us_khb_dev;
grant execute on type::sc_khb_srv.cn_nv4000 to us_khb_dev;
grant execute on type::sc_khb_srv.cn_nvmax to us_khb_dev;
grant execute on type::sc_khb_srv.cnt_n15 to us_khb_dev;
grant execute on type::sc_khb_srv.cntom_n15 to us_khb_dev;
grant execute on type::sc_khb_srv.cours_v100 to us_khb_dev;
grant execute on type::sc_khb_srv.cpcty_d25_15 to us_khb_dev;
grant execute on type::sc_khb_srv.crdnt_v500 to us_khb_dev;
grant execute on type::sc_khb_srv.ct_n18 to us_khb_dev;
grant execute on type::sc_khb_srv.cycle_v20 to us_khb_dev;
grant execute on type::sc_khb_srv.day_nv100 to us_khb_dev;
grant execute on type::sc_khb_srv.de_v10 to us_khb_dev;
grant execute on type::sc_khb_srv.dt to us_khb_dev;
grant execute on type::sc_khb_srv.dt_v10 to us_khb_dev;
grant execute on type::sc_khb_srv.email_v320 to us_khb_dev;
grant execute on type::sc_khb_srv.fee_n18 to us_khb_dev;
grant execute on type::sc_khb_srv.fxno_v30 to us_khb_dev;
grant execute on type::sc_khb_srv.hm_c4 to us_khb_dev;
grant execute on type::sc_khb_srv.hms_c6 to us_khb_dev;
grant execute on type::sc_khb_srv.id_nv100 to us_khb_dev;
grant execute on type::sc_khb_srv.innb_v20 to us_khb_dev;
grant execute on type::sc_khb_srv.ip_v100 to us_khb_dev;
grant execute on type::sc_khb_srv.lat_d12_10 to us_khb_dev;
grant execute on type::sc_khb_srv.list_nv1000 to us_khb_dev;
grant execute on type::sc_khb_srv.lot_d13_10 to us_khb_dev;
grant execute on type::sc_khb_srv.lotno_nv100 to us_khb_dev;
grant execute on type::sc_khb_srv.mno_n4 to us_khb_dev;
grant execute on type::sc_khb_srv.mt_c2 to us_khb_dev;
grant execute on type::sc_khb_srv.nm_nv500 to us_khb_dev;
grant execute on type::sc_khb_srv.no_n15 to us_khb_dev;
grant execute on type::sc_khb_srv.no_v200 to us_khb_dev;
grant execute on type::sc_khb_srv.ordr_n5 to us_khb_dev;
grant execute on type::sc_khb_srv.password_v500 to us_khb_dev;
grant execute on type::sc_khb_srv.pc_n10 to us_khb_dev;
grant execute on type::sc_khb_srv.pd_nv50 to us_khb_dev;
grant execute on type::sc_khb_srv.pk_n18 to us_khb_dev;
grant execute on type::sc_khb_srv.premium_n18 to us_khb_dev;
grant execute on type::sc_khb_srv.pyeong_d19_9 to us_khb_dev;
grant execute on type::sc_khb_srv.rank_n5 to us_khb_dev;
grant execute on type::sc_khb_srv.rt_d19_9 to us_khb_dev;
grant execute on type::sc_khb_srv.size_v20 to us_khb_dev;
grant execute on type::sc_khb_srv.sn_v200 to us_khb_dev;
grant execute on type::sc_khb_srv.sno_n4 to us_khb_dev;
grant execute on type::sc_khb_srv.telno_v30 to us_khb_dev;
grant execute on type::sc_khb_srv.totar_d19_9 to us_khb_dev;
grant execute on type::sc_khb_srv.url_nv4000 to us_khb_dev;
grant execute on type::sc_khb_srv.vl_d25_15 to us_khb_dev;
grant execute on type::sc_khb_srv.vl_v100 to us_khb_dev;
grant execute on type::sc_khb_srv.year_c4 to us_khb_dev;
grant execute on type::sc_khb_srv.ym_c6 to us_khb_dev;
grant execute on type::sc_khb_srv.yn_c1 to us_khb_dev;
grant execute on type::sc_khb_srv.zip_c5 to us_khb_dev;


/*us_khb_exif*/
grant execute on type::sc_khb_srv.addr_nv1000 to us_khb_exif;
grant execute on type::sc_khb_srv.amt_n18 to us_khb_exif;
grant execute on type::sc_khb_srv.area_d19_9 to us_khb_exif;
grant execute on type::sc_khb_srv.cd_v20 to us_khb_exif;
grant execute on type::sc_khb_srv.cn_nv4000 to us_khb_exif;
grant execute on type::sc_khb_srv.cn_nvmax to us_khb_exif;
grant execute on type::sc_khb_srv.cnt_n15 to us_khb_exif;
grant execute on type::sc_khb_srv.cntom_n15 to us_khb_exif;
grant execute on type::sc_khb_srv.cours_v100 to us_khb_exif;
grant execute on type::sc_khb_srv.cpcty_d25_15 to us_khb_exif;
grant execute on type::sc_khb_srv.crdnt_v500 to us_khb_exif;
grant execute on type::sc_khb_srv.ct_n18 to us_khb_exif;
grant execute on type::sc_khb_srv.cycle_v20 to us_khb_exif;
grant execute on type::sc_khb_srv.day_nv100 to us_khb_exif;
grant execute on type::sc_khb_srv.de_v10 to us_khb_exif;
grant execute on type::sc_khb_srv.dt to us_khb_exif;
grant execute on type::sc_khb_srv.dt_v10 to us_khb_exif;
grant execute on type::sc_khb_srv.email_v320 to us_khb_exif;
grant execute on type::sc_khb_srv.fee_n18 to us_khb_exif;
grant execute on type::sc_khb_srv.fxno_v30 to us_khb_exif;
grant execute on type::sc_khb_srv.hm_c4 to us_khb_exif;
grant execute on type::sc_khb_srv.hms_c6 to us_khb_exif;
grant execute on type::sc_khb_srv.id_nv100 to us_khb_exif;
grant execute on type::sc_khb_srv.innb_v20 to us_khb_exif;
grant execute on type::sc_khb_srv.ip_v100 to us_khb_exif;
grant execute on type::sc_khb_srv.lat_d12_10 to us_khb_exif;
grant execute on type::sc_khb_srv.list_nv1000 to us_khb_exif;
grant execute on type::sc_khb_srv.lot_d13_10 to us_khb_exif;
grant execute on type::sc_khb_srv.lotno_nv100 to us_khb_exif;
grant execute on type::sc_khb_srv.mno_n4 to us_khb_exif;
grant execute on type::sc_khb_srv.mt_c2 to us_khb_exif;
grant execute on type::sc_khb_srv.nm_nv500 to us_khb_exif;
grant execute on type::sc_khb_srv.no_n15 to us_khb_exif;
grant execute on type::sc_khb_srv.no_v200 to us_khb_exif;
grant execute on type::sc_khb_srv.ordr_n5 to us_khb_exif;
grant execute on type::sc_khb_srv.password_v500 to us_khb_exif;
grant execute on type::sc_khb_srv.pc_n10 to us_khb_exif;
grant execute on type::sc_khb_srv.pd_nv50 to us_khb_exif;
grant execute on type::sc_khb_srv.pk_n18 to us_khb_exif;
grant execute on type::sc_khb_srv.premium_n18 to us_khb_exif;
grant execute on type::sc_khb_srv.pyeong_d19_9 to us_khb_exif;
grant execute on type::sc_khb_srv.rank_n5 to us_khb_exif;
grant execute on type::sc_khb_srv.rt_d19_9 to us_khb_exif;
grant execute on type::sc_khb_srv.size_v20 to us_khb_exif;
grant execute on type::sc_khb_srv.sn_v200 to us_khb_exif;
grant execute on type::sc_khb_srv.sno_n4 to us_khb_exif;
grant execute on type::sc_khb_srv.telno_v30 to us_khb_exif;
grant execute on type::sc_khb_srv.totar_d19_9 to us_khb_exif;
grant execute on type::sc_khb_srv.url_nv4000 to us_khb_exif;
grant execute on type::sc_khb_srv.vl_d25_15 to us_khb_exif;
grant execute on type::sc_khb_srv.vl_v100 to us_khb_exif;
grant execute on type::sc_khb_srv.year_c4 to us_khb_exif;
grant execute on type::sc_khb_srv.ym_c6 to us_khb_exif;
grant execute on type::sc_khb_srv.yn_c1 to us_khb_exif;
grant execute on type::sc_khb_srv.zip_c5 to us_khb_exif;


/*us_khb_magnt*/
grant execute on type::sc_khb_srv.addr_nv1000 to us_khb_magnt;
grant execute on type::sc_khb_srv.amt_n18 to us_khb_magnt;
grant execute on type::sc_khb_srv.area_d19_9 to us_khb_magnt;
grant execute on type::sc_khb_srv.cd_v20 to us_khb_magnt;
grant execute on type::sc_khb_srv.cn_nv4000 to us_khb_magnt;
grant execute on type::sc_khb_srv.cn_nvmax to us_khb_magnt;
grant execute on type::sc_khb_srv.cnt_n15 to us_khb_magnt;
grant execute on type::sc_khb_srv.cntom_n15 to us_khb_magnt;
grant execute on type::sc_khb_srv.cours_v100 to us_khb_magnt;
grant execute on type::sc_khb_srv.cpcty_d25_15 to us_khb_magnt;
grant execute on type::sc_khb_srv.crdnt_v500 to us_khb_magnt;
grant execute on type::sc_khb_srv.ct_n18 to us_khb_magnt;
grant execute on type::sc_khb_srv.cycle_v20 to us_khb_magnt;
grant execute on type::sc_khb_srv.day_nv100 to us_khb_magnt;
grant execute on type::sc_khb_srv.de_v10 to us_khb_magnt;
grant execute on type::sc_khb_srv.dt to us_khb_magnt;
grant execute on type::sc_khb_srv.dt_v10 to us_khb_magnt;
grant execute on type::sc_khb_srv.email_v320 to us_khb_magnt;
grant execute on type::sc_khb_srv.fee_n18 to us_khb_magnt;
grant execute on type::sc_khb_srv.fxno_v30 to us_khb_magnt;
grant execute on type::sc_khb_srv.hm_c4 to us_khb_magnt;
grant execute on type::sc_khb_srv.hms_c6 to us_khb_magnt;
grant execute on type::sc_khb_srv.id_nv100 to us_khb_magnt;
grant execute on type::sc_khb_srv.innb_v20 to us_khb_magnt;
grant execute on type::sc_khb_srv.ip_v100 to us_khb_magnt;
grant execute on type::sc_khb_srv.lat_d12_10 to us_khb_magnt;
grant execute on type::sc_khb_srv.list_nv1000 to us_khb_magnt;
grant execute on type::sc_khb_srv.lot_d13_10 to us_khb_magnt;
grant execute on type::sc_khb_srv.lotno_nv100 to us_khb_magnt;
grant execute on type::sc_khb_srv.mno_n4 to us_khb_magnt;
grant execute on type::sc_khb_srv.mt_c2 to us_khb_magnt;
grant execute on type::sc_khb_srv.nm_nv500 to us_khb_magnt;
grant execute on type::sc_khb_srv.no_n15 to us_khb_magnt;
grant execute on type::sc_khb_srv.no_v200 to us_khb_magnt;
grant execute on type::sc_khb_srv.ordr_n5 to us_khb_magnt;
grant execute on type::sc_khb_srv.password_v500 to us_khb_magnt;
grant execute on type::sc_khb_srv.pc_n10 to us_khb_magnt;
grant execute on type::sc_khb_srv.pd_nv50 to us_khb_magnt;
grant execute on type::sc_khb_srv.pk_n18 to us_khb_magnt;
grant execute on type::sc_khb_srv.premium_n18 to us_khb_magnt;
grant execute on type::sc_khb_srv.pyeong_d19_9 to us_khb_magnt;
grant execute on type::sc_khb_srv.rank_n5 to us_khb_magnt;
grant execute on type::sc_khb_srv.rt_d19_9 to us_khb_magnt;
grant execute on type::sc_khb_srv.size_v20 to us_khb_magnt;
grant execute on type::sc_khb_srv.sn_v200 to us_khb_magnt;
grant execute on type::sc_khb_srv.sno_n4 to us_khb_magnt;
grant execute on type::sc_khb_srv.telno_v30 to us_khb_magnt;
grant execute on type::sc_khb_srv.totar_d19_9 to us_khb_magnt;
grant execute on type::sc_khb_srv.url_nv4000 to us_khb_magnt;
grant execute on type::sc_khb_srv.vl_d25_15 to us_khb_magnt;
grant execute on type::sc_khb_srv.vl_v100 to us_khb_magnt;
grant execute on type::sc_khb_srv.year_c4 to us_khb_magnt;
grant execute on type::sc_khb_srv.ym_c6 to us_khb_magnt;
grant execute on type::sc_khb_srv.yn_c1 to us_khb_magnt;
grant execute on type::sc_khb_srv.zip_c5 to us_khb_magnt;


/*us_khb_mptl*/
grant execute on type::sc_khb_srv.addr_nv1000 to us_khb_mptl;
grant execute on type::sc_khb_srv.amt_n18 to us_khb_mptl;
grant execute on type::sc_khb_srv.area_d19_9 to us_khb_mptl;
grant execute on type::sc_khb_srv.cd_v20 to us_khb_mptl;
grant execute on type::sc_khb_srv.cn_nv4000 to us_khb_mptl;
grant execute on type::sc_khb_srv.cn_nvmax to us_khb_mptl;
grant execute on type::sc_khb_srv.cnt_n15 to us_khb_mptl;
grant execute on type::sc_khb_srv.cntom_n15 to us_khb_mptl;
grant execute on type::sc_khb_srv.cours_v100 to us_khb_mptl;
grant execute on type::sc_khb_srv.cpcty_d25_15 to us_khb_mptl;
grant execute on type::sc_khb_srv.crdnt_v500 to us_khb_mptl;
grant execute on type::sc_khb_srv.ct_n18 to us_khb_mptl;
grant execute on type::sc_khb_srv.cycle_v20 to us_khb_mptl;
grant execute on type::sc_khb_srv.day_nv100 to us_khb_mptl;
grant execute on type::sc_khb_srv.de_v10 to us_khb_mptl;
grant execute on type::sc_khb_srv.dt to us_khb_mptl;
grant execute on type::sc_khb_srv.dt_v10 to us_khb_mptl;
grant execute on type::sc_khb_srv.email_v320 to us_khb_mptl;
grant execute on type::sc_khb_srv.fee_n18 to us_khb_mptl;
grant execute on type::sc_khb_srv.fxno_v30 to us_khb_mptl;
grant execute on type::sc_khb_srv.hm_c4 to us_khb_mptl;
grant execute on type::sc_khb_srv.hms_c6 to us_khb_mptl;
grant execute on type::sc_khb_srv.id_nv100 to us_khb_mptl;
grant execute on type::sc_khb_srv.innb_v20 to us_khb_mptl;
grant execute on type::sc_khb_srv.ip_v100 to us_khb_mptl;
grant execute on type::sc_khb_srv.lat_d12_10 to us_khb_mptl;
grant execute on type::sc_khb_srv.list_nv1000 to us_khb_mptl;
grant execute on type::sc_khb_srv.lot_d13_10 to us_khb_mptl;
grant execute on type::sc_khb_srv.lotno_nv100 to us_khb_mptl;
grant execute on type::sc_khb_srv.mno_n4 to us_khb_mptl;
grant execute on type::sc_khb_srv.mt_c2 to us_khb_mptl;
grant execute on type::sc_khb_srv.nm_nv500 to us_khb_mptl;
grant execute on type::sc_khb_srv.no_n15 to us_khb_mptl;
grant execute on type::sc_khb_srv.no_v200 to us_khb_mptl;
grant execute on type::sc_khb_srv.ordr_n5 to us_khb_mptl;
grant execute on type::sc_khb_srv.password_v500 to us_khb_mptl;
grant execute on type::sc_khb_srv.pc_n10 to us_khb_mptl;
grant execute on type::sc_khb_srv.pd_nv50 to us_khb_mptl;
grant execute on type::sc_khb_srv.pk_n18 to us_khb_mptl;
grant execute on type::sc_khb_srv.premium_n18 to us_khb_mptl;
grant execute on type::sc_khb_srv.pyeong_d19_9 to us_khb_mptl;
grant execute on type::sc_khb_srv.rank_n5 to us_khb_mptl;
grant execute on type::sc_khb_srv.rt_d19_9 to us_khb_mptl;
grant execute on type::sc_khb_srv.size_v20 to us_khb_mptl;
grant execute on type::sc_khb_srv.sn_v200 to us_khb_mptl;
grant execute on type::sc_khb_srv.sno_n4 to us_khb_mptl;
grant execute on type::sc_khb_srv.telno_v30 to us_khb_mptl;
grant execute on type::sc_khb_srv.totar_d19_9 to us_khb_mptl;
grant execute on type::sc_khb_srv.url_nv4000 to us_khb_mptl;
grant execute on type::sc_khb_srv.vl_d25_15 to us_khb_mptl;
grant execute on type::sc_khb_srv.vl_v100 to us_khb_mptl;
grant execute on type::sc_khb_srv.year_c4 to us_khb_mptl;
grant execute on type::sc_khb_srv.ym_c6 to us_khb_mptl;
grant execute on type::sc_khb_srv.yn_c1 to us_khb_mptl;
grant execute on type::sc_khb_srv.zip_c5 to us_khb_mptl;


/*us_khb_report*/
grant execute on type::sc_khb_srv.addr_nv1000 to us_khb_report;
grant execute on type::sc_khb_srv.amt_n18 to us_khb_report;
grant execute on type::sc_khb_srv.area_d19_9 to us_khb_report;
grant execute on type::sc_khb_srv.cd_v20 to us_khb_report;
grant execute on type::sc_khb_srv.cn_nv4000 to us_khb_report;
grant execute on type::sc_khb_srv.cn_nvmax to us_khb_report;
grant execute on type::sc_khb_srv.cnt_n15 to us_khb_report;
grant execute on type::sc_khb_srv.cntom_n15 to us_khb_report;
grant execute on type::sc_khb_srv.cours_v100 to us_khb_report;
grant execute on type::sc_khb_srv.cpcty_d25_15 to us_khb_report;
grant execute on type::sc_khb_srv.crdnt_v500 to us_khb_report;
grant execute on type::sc_khb_srv.ct_n18 to us_khb_report;
grant execute on type::sc_khb_srv.cycle_v20 to us_khb_report;
grant execute on type::sc_khb_srv.day_nv100 to us_khb_report;
grant execute on type::sc_khb_srv.de_v10 to us_khb_report;
grant execute on type::sc_khb_srv.dt to us_khb_report;
grant execute on type::sc_khb_srv.dt_v10 to us_khb_report;
grant execute on type::sc_khb_srv.email_v320 to us_khb_report;
grant execute on type::sc_khb_srv.fee_n18 to us_khb_report;
grant execute on type::sc_khb_srv.fxno_v30 to us_khb_report;
grant execute on type::sc_khb_srv.hm_c4 to us_khb_report;
grant execute on type::sc_khb_srv.hms_c6 to us_khb_report;
grant execute on type::sc_khb_srv.id_nv100 to us_khb_report;
grant execute on type::sc_khb_srv.innb_v20 to us_khb_report;
grant execute on type::sc_khb_srv.ip_v100 to us_khb_report;
grant execute on type::sc_khb_srv.lat_d12_10 to us_khb_report;
grant execute on type::sc_khb_srv.list_nv1000 to us_khb_report;
grant execute on type::sc_khb_srv.lot_d13_10 to us_khb_report;
grant execute on type::sc_khb_srv.lotno_nv100 to us_khb_report;
grant execute on type::sc_khb_srv.mno_n4 to us_khb_report;
grant execute on type::sc_khb_srv.mt_c2 to us_khb_report;
grant execute on type::sc_khb_srv.nm_nv500 to us_khb_report;
grant execute on type::sc_khb_srv.no_n15 to us_khb_report;
grant execute on type::sc_khb_srv.no_v200 to us_khb_report;
grant execute on type::sc_khb_srv.ordr_n5 to us_khb_report;
grant execute on type::sc_khb_srv.password_v500 to us_khb_report;
grant execute on type::sc_khb_srv.pc_n10 to us_khb_report;
grant execute on type::sc_khb_srv.pd_nv50 to us_khb_report;
grant execute on type::sc_khb_srv.pk_n18 to us_khb_report;
grant execute on type::sc_khb_srv.premium_n18 to us_khb_report;
grant execute on type::sc_khb_srv.pyeong_d19_9 to us_khb_report;
grant execute on type::sc_khb_srv.rank_n5 to us_khb_report;
grant execute on type::sc_khb_srv.rt_d19_9 to us_khb_report;
grant execute on type::sc_khb_srv.size_v20 to us_khb_report;
grant execute on type::sc_khb_srv.sn_v200 to us_khb_report;
grant execute on type::sc_khb_srv.sno_n4 to us_khb_report;
grant execute on type::sc_khb_srv.telno_v30 to us_khb_report;
grant execute on type::sc_khb_srv.totar_d19_9 to us_khb_report;
grant execute on type::sc_khb_srv.url_nv4000 to us_khb_report;
grant execute on type::sc_khb_srv.vl_d25_15 to us_khb_report;
grant execute on type::sc_khb_srv.vl_v100 to us_khb_report;
grant execute on type::sc_khb_srv.year_c4 to us_khb_report;
grant execute on type::sc_khb_srv.ym_c6 to us_khb_report;
grant execute on type::sc_khb_srv.yn_c1 to us_khb_report;
grant execute on type::sc_khb_srv.zip_c5 to us_khb_report;


/*us_khb_srch*/
grant execute on type::sc_khb_srv.addr_nv1000 to us_khb_srch;
grant execute on type::sc_khb_srv.amt_n18 to us_khb_srch;
grant execute on type::sc_khb_srv.area_d19_9 to us_khb_srch;
grant execute on type::sc_khb_srv.cd_v20 to us_khb_srch;
grant execute on type::sc_khb_srv.cn_nv4000 to us_khb_srch;
grant execute on type::sc_khb_srv.cn_nvmax to us_khb_srch;
grant execute on type::sc_khb_srv.cnt_n15 to us_khb_srch;
grant execute on type::sc_khb_srv.cntom_n15 to us_khb_srch;
grant execute on type::sc_khb_srv.cours_v100 to us_khb_srch;
grant execute on type::sc_khb_srv.cpcty_d25_15 to us_khb_srch;
grant execute on type::sc_khb_srv.crdnt_v500 to us_khb_srch;
grant execute on type::sc_khb_srv.ct_n18 to us_khb_srch;
grant execute on type::sc_khb_srv.cycle_v20 to us_khb_srch;
grant execute on type::sc_khb_srv.day_nv100 to us_khb_srch;
grant execute on type::sc_khb_srv.de_v10 to us_khb_srch;
grant execute on type::sc_khb_srv.dt to us_khb_srch;
grant execute on type::sc_khb_srv.dt_v10 to us_khb_srch;
grant execute on type::sc_khb_srv.email_v320 to us_khb_srch;
grant execute on type::sc_khb_srv.fee_n18 to us_khb_srch;
grant execute on type::sc_khb_srv.fxno_v30 to us_khb_srch;
grant execute on type::sc_khb_srv.hm_c4 to us_khb_srch;
grant execute on type::sc_khb_srv.hms_c6 to us_khb_srch;
grant execute on type::sc_khb_srv.id_nv100 to us_khb_srch;
grant execute on type::sc_khb_srv.innb_v20 to us_khb_srch;
grant execute on type::sc_khb_srv.ip_v100 to us_khb_srch;
grant execute on type::sc_khb_srv.lat_d12_10 to us_khb_srch;
grant execute on type::sc_khb_srv.list_nv1000 to us_khb_srch;
grant execute on type::sc_khb_srv.lot_d13_10 to us_khb_srch;
grant execute on type::sc_khb_srv.lotno_nv100 to us_khb_srch;
grant execute on type::sc_khb_srv.mno_n4 to us_khb_srch;
grant execute on type::sc_khb_srv.mt_c2 to us_khb_srch;
grant execute on type::sc_khb_srv.nm_nv500 to us_khb_srch;
grant execute on type::sc_khb_srv.no_n15 to us_khb_srch;
grant execute on type::sc_khb_srv.no_v200 to us_khb_srch;
grant execute on type::sc_khb_srv.ordr_n5 to us_khb_srch;
grant execute on type::sc_khb_srv.password_v500 to us_khb_srch;
grant execute on type::sc_khb_srv.pc_n10 to us_khb_srch;
grant execute on type::sc_khb_srv.pd_nv50 to us_khb_srch;
grant execute on type::sc_khb_srv.pk_n18 to us_khb_srch;
grant execute on type::sc_khb_srv.premium_n18 to us_khb_srch;
grant execute on type::sc_khb_srv.pyeong_d19_9 to us_khb_srch;
grant execute on type::sc_khb_srv.rank_n5 to us_khb_srch;
grant execute on type::sc_khb_srv.rt_d19_9 to us_khb_srch;
grant execute on type::sc_khb_srv.size_v20 to us_khb_srch;
grant execute on type::sc_khb_srv.sn_v200 to us_khb_srch;
grant execute on type::sc_khb_srv.sno_n4 to us_khb_srch;
grant execute on type::sc_khb_srv.telno_v30 to us_khb_srch;
grant execute on type::sc_khb_srv.totar_d19_9 to us_khb_srch;
grant execute on type::sc_khb_srv.url_nv4000 to us_khb_srch;
grant execute on type::sc_khb_srv.vl_d25_15 to us_khb_srch;
grant execute on type::sc_khb_srv.vl_v100 to us_khb_srch;
grant execute on type::sc_khb_srv.year_c4 to us_khb_srch;
grant execute on type::sc_khb_srv.ym_c6 to us_khb_srch;
grant execute on type::sc_khb_srv.yn_c1 to us_khb_srch;
grant execute on type::sc_khb_srv.zip_c5 to us_khb_srch;


/*us_khb_std*/
grant execute on type::sc_khb_srv.addr_nv1000 to us_khb_std;
grant execute on type::sc_khb_srv.amt_n18 to us_khb_std;
grant execute on type::sc_khb_srv.area_d19_9 to us_khb_std;
grant execute on type::sc_khb_srv.cd_v20 to us_khb_std;
grant execute on type::sc_khb_srv.cn_nv4000 to us_khb_std;
grant execute on type::sc_khb_srv.cn_nvmax to us_khb_std;
grant execute on type::sc_khb_srv.cnt_n15 to us_khb_std;
grant execute on type::sc_khb_srv.cntom_n15 to us_khb_std;
grant execute on type::sc_khb_srv.cours_v100 to us_khb_std;
grant execute on type::sc_khb_srv.cpcty_d25_15 to us_khb_std;
grant execute on type::sc_khb_srv.crdnt_v500 to us_khb_std;
grant execute on type::sc_khb_srv.ct_n18 to us_khb_std;
grant execute on type::sc_khb_srv.cycle_v20 to us_khb_std;
grant execute on type::sc_khb_srv.day_nv100 to us_khb_std;
grant execute on type::sc_khb_srv.de_v10 to us_khb_std;
grant execute on type::sc_khb_srv.dt to us_khb_std;
grant execute on type::sc_khb_srv.dt_v10 to us_khb_std;
grant execute on type::sc_khb_srv.email_v320 to us_khb_std;
grant execute on type::sc_khb_srv.fee_n18 to us_khb_std;
grant execute on type::sc_khb_srv.fxno_v30 to us_khb_std;
grant execute on type::sc_khb_srv.hm_c4 to us_khb_std;
grant execute on type::sc_khb_srv.hms_c6 to us_khb_std;
grant execute on type::sc_khb_srv.id_nv100 to us_khb_std;
grant execute on type::sc_khb_srv.innb_v20 to us_khb_std;
grant execute on type::sc_khb_srv.ip_v100 to us_khb_std;
grant execute on type::sc_khb_srv.lat_d12_10 to us_khb_std;
grant execute on type::sc_khb_srv.list_nv1000 to us_khb_std;
grant execute on type::sc_khb_srv.lot_d13_10 to us_khb_std;
grant execute on type::sc_khb_srv.lotno_nv100 to us_khb_std;
grant execute on type::sc_khb_srv.mno_n4 to us_khb_std;
grant execute on type::sc_khb_srv.mt_c2 to us_khb_std;
grant execute on type::sc_khb_srv.nm_nv500 to us_khb_std;
grant execute on type::sc_khb_srv.no_n15 to us_khb_std;
grant execute on type::sc_khb_srv.no_v200 to us_khb_std;
grant execute on type::sc_khb_srv.ordr_n5 to us_khb_std;
grant execute on type::sc_khb_srv.password_v500 to us_khb_std;
grant execute on type::sc_khb_srv.pc_n10 to us_khb_std;
grant execute on type::sc_khb_srv.pd_nv50 to us_khb_std;
grant execute on type::sc_khb_srv.pk_n18 to us_khb_std; 
grant execute on type::sc_khb_srv.premium_n18 to us_khb_std;
grant execute on type::sc_khb_srv.pyeong_d19_9 to us_khb_std;
grant execute on type::sc_khb_srv.rank_n5 to us_khb_std;
grant execute on type::sc_khb_srv.rt_d19_9 to us_khb_std;
grant execute on type::sc_khb_srv.size_v20 to us_khb_std;
grant execute on type::sc_khb_srv.sn_v200 to us_khb_std;
grant execute on type::sc_khb_srv.sno_n4 to us_khb_std;
grant execute on type::sc_khb_srv.telno_v30 to us_khb_std;
grant execute on type::sc_khb_srv.totar_d19_9 to us_khb_std;
grant execute on type::sc_khb_srv.url_nv4000 to us_khb_std;
grant execute on type::sc_khb_srv.vl_d25_15 to us_khb_std;
grant execute on type::sc_khb_srv.vl_v100 to us_khb_std;
grant execute on type::sc_khb_srv.year_c4 to us_khb_std;
grant execute on type::sc_khb_srv.ym_c6 to us_khb_std;
grant execute on type::sc_khb_srv.yn_c1 to us_khb_std;
grant execute on type::sc_khb_srv.zip_c5 to us_khb_std;

